-- criar o banco de dados 
CREATE DATABASE DB_2IP;

USE DB_2IP;

 CREATE TABLE IF NOT EXISTS TB_CEP(

    ID_CEP  INT PRIMARY KEY AUTO_INCREMENT ,
    CEP     VARCHAR(10)   ,
    RUA     VARCHAR (100) ,
    NUMERO  VARCHAR(4) ,
    COMP    VARCHAR(60),
    BAIRRO  VARCHAR(100),
    CIDADE  VARCHAR(100),
    UF      CHAR(2)
 ); 

 CREATE TABLE IF NOT EXISTS TB_PESSOAl(

      ID_PESSOA INT PRIMARY KEY AUTO_INCREMENT,
      NOME VARCHAR(120),
      DATANASC DATETIME,
      EMAIL VARCHAR(60),
      TELEFONE VARCHAR(20),
      ASSUNTO VARCHAR(30),
      MENSAGEM VARCHAR(450),
      SENHA VARCHAR(36),
      CPF VARCHAR(12),
      RG VARCHAR(12),
      ID_CEP INT,
      FOREIGN KEY(ID_CEP) REFERENCES TB_CEP(ID_CEP) 
      
 )
